namespace LightADO;

/// <summary>
/// This class will handle any issues generated by LightAdo.net Package.
/// </summary>
public class LightAdoExcption : Exception
{
    public LightAdoExcption(string message) => this.Message = message;

    public LightAdoExcption(Exception ex, string message = "An error occurred, check the error details for more.")
    {
        this.Message = message;
        this.Details = ex;
    }

    /// <summary>
    /// Gets or sets the Message.
    /// </summary>
    public new string Message { get; private set; }


    /// <summary>
    /// Gets or sets the Exception details
    /// </summary>
    public Exception Details { get; set; }
}